language: node_js
node_js:
  - "8.0"

branches:
  only:
    - master

#before_script:
 # - npm install -g firebase-tools
 # - npm install -g gatsby

script:
  - gatsby build

after_success:
  - firebase deploy --token=${AIzaSyD9urGWGzFRi7cmrvd7RGZ2dadR_W2SZzU}